### PR TITLE
Update Overview.md

### PR DESCRIPTION
**Pull request by EricForgy**
If you prefer this, I can change the remaining items.

### CODE REVIEW

**Comment by aviks** [comment]
@EricForgy  Thanks a lot for this!

@astrieanna @zachallaun How is this hosted? Can one of you push this out?

**Comment by zachallaun** [comment]
Great question. Embarrassingly enough, I don't remember. @danielmendel ?

**Comment by despeset** [comment]
@zachallaun @astrieanna  @aviks @IainNZ 

The site is hosted on Github Pages - in theory the deployment steps are to run `make` on master, and then commit the resulting `index.html` to the `gh-pages` branch and push.  However, there are some problems with this right now.

The way the `Makefile` builds the site is by curling the contents of `<modulename>.jl/docs/<moduleame>.md` from each of the webstack repos (here's a [diff](https://gist.github.com/danielmendel/6beeaf1d03e097d1d6c9) that updates these requests to point at the JuliaWeb org).  It looks like these files have all been removed (ex: https://github.com/JuliaWeb/Morsel.jl/commit/5f12df615a9f5f3d6f859b97adedc72bfdbec86c).  We could update the `Makefile` to point at the root `readme.md` for each of these, but it could awkward since they can include other boilerplate, such as the hacker school logo.  Perhaps we should update the `Makefile` to filter out the last code block, or everything below a horizontal rule at the bottom of the Readme files?

As a stop-gap, `index.html` in the `gh-pages` branch could be modified and pushed manually.

**Comment by IainNZ** [comment]
In that case, I'd advocate simplifying the website to just basically enumerating the packages, and maybe even extend it to include other JuliaWeb packages, no make files or such magic.

**Pull request merged**
